
-- define emotes
-- use the custom emotes admin action to test emotes on-the-fly
-- animation list: http://docs.ragepluginhook.net/html/62951c37-a440-478c-b389-c471230ddfc5.htm

local cfg = {}

-- map of emote_name => {upper,seq,looping} and an optional permissions property
-- seq can also be a task definition, check the examples below
cfg.emotes = {
	
    ["Levantar as mãos"] = {true,{{"random@mugging3", "handsup_standing_base", 1}}, true},
	["Não"] = {true, {{"gestures@f@standing@casual","gesture_head_no",1}}, false},
	["Droga!"] = {true, {{"gestures@f@standing@casual","gesture_damn",1}}, false},
	["Dançar"] = {false, {{"rcmnigel1bnmt_1b","dance_intro_tyler",1},{"rcmnigel1bnmt_1b","dance_loop_tyler",1}}, false},
	["Acenar"] = {false, {{"friends@frj@ig_1", "wave_a",1}}, false},
	["Saudação"] = {true,{{"mp_player_int_uppersalute","mp_player_int_salute",1}},false},
	["Rock"] = {true,{{"mp_player_introck","mp_player_int_rock",1}},false},
	
	["Sentar na cadeira"] = {false, {task="PROP_HUMAN_SEAT_CHAIR_MP_PLAYER"}, false},
	["Policia"] = {false, {task="WORLD_HUMAN_COP_IDLES"}, false},
	["Olhar no Binoculo"] = {false, {task="WORLD_HUMAN_BINOCULARS"}, false},
	["Bater palmas"] = {false, {task="WORLD_HUMAN_CHEERING"}, false},
	["Beber"] = {false, {task="WORLD_HUMAN_DRINKING"}, false},
	["Fumar"] = {false, {task="WORLD_HUMAN_SMOKING"}, false},
	["Filmar"] = {false, {task="WORLD_HUMAN_MOBILE_FILM_SHOCKING"}, false},
	["Ficar de Guarda"] = {false, {task="WORLD_HUMAN_GUARD_STAND"}, false},
	["Martelar"] = {false, {task="WORLD_HUMAN_HAMMERING"}, false},
	--  ["Hangout"] = {false, {task="WORLD_HUMAN_HANG_OUT_STREET"}, false},
	-- ["Hiker"] = {false, {task="WORLD_HUMAN_HIKER_STANDING"}, false},
	["Ficar Estatua"] = {false, {task="WORLD_HUMAN_HUMAN_STATUE"}, false},
	["Corrida"] = {false, {task="WORLD_HUMAN_JOG_STANDING"}, false},
	["Inclinar-se"] = {false, {task="WORLD_HUMAN_LEANING"}, false},
	["Alongar-se"] = {false, {task="WORLD_HUMAN_MUSCLE_FLEX"}, false},
	["Camera"] = {false, {task="WORLD_HUMAN_PAPARAZZI"}, false},
	["Sentar"] = {false, {task="WORLD_HUMAN_PICNIC"}, false},
	["Prostituta 1"] = {false, {task="WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}, false},
	["Prostituta 2"] = {false, {task="WORLD_HUMAN_PROSTITUTE_LOW_CLASS"}, false},
	["Fazer Flexões"] = {false, {task="WORLD_HUMAN_PUSH_UPS"}, false},
	["Fazer Abdominais"] = {false, {task="WORLD_HUMAN_SIT_UPS"}, false},
	["Pescar"] = {false, {task="WORLD_HUMAN_STAND_FISHING"}, false},
	["Impaciente"] = {false, {task="WORLD_HUMAN_STAND_IMPATIENT"}, false},
	["Mexer no celular"] = {false, {task="WORLD_HUMAN_STAND_MOBILE"}, false},
	["Dançar 2"] = {false, {task="WORLD_HUMAN_STRIP_WATCH_STAND"}, false},
	["Deitar 1"] = {false, {task="WORLD_HUMAN_SUNBATHE_BACK"}, false},
	["Deitar 2"] = {false, {task="WORLD_HUMAN_SUNBATHE"}, false},
	["Soldar"] = {false, {task="WORLD_HUMAN_WELDING"}, false},
	["Examinar corpo"] = {false, {task="CODE_HUMAN_MEDIC_KNEEL"}, false},
	["Controlar Multidão"] = {false, {task="CODE_HUMAN_POLICE_CROWD_CONTROL"}, false},
	["Investigar"] = {false, {task="CODE_HUMAN_POLICE_INVESTIGATE"}, false},
	["Fazer Yoga"] = {false, {task="WORLD_HUMAN_YOGA"}, false},
	["Chupeta H"] = {false,{{"oddjobs@towing","m_blow_job_loop",1}},false},
	["Chupeta M"] = {false,{{"oddjobs@towing","f_blow_job_loop",1}},false},
	["Sexo H"] = {false,{{"mini@prostitutes@sexlow_veh","low_car_sex_loop_player",1}},false},
	["Sexo M"] = {false,{{"mini@prostitutes@sexlow_veh","low_car_sex_loop_female",1}},false},
	["Punheta"] = {true,{{"mp_player_int_upperwank","mp_player_int_wank_01",1}},false},
	["Dar o cu"] = {false,{{"rcmpaparazzo_2","shag_loop_poppy",2}},true},
	["Come o cu"] = {false,{{"rcmpaparazzo_2","shag_loop_a",2}},true},
	["Beijo Boca"] = {true,{{"mp_ped_interaction","kisses_guy_a",1}},false},
	["Balança peito"] = {false,{{"mini@strip_club@backroom@","stripper_b_backroom_idle_b",1}},false},
	["Strip de esquina"] = {false,{{"mini@strip_club@idles@stripper","stripper_idle_02",1}},false},
	["Sentar mexer celular"] = {false,{{"anim@heists@prison_heistunfinished_biztarget_idle","target_idle",1}},false},
	["Escutar coracao"] = {false,{{"mini@safe_cracking","idle_base",1}},false},
	["Churrasco"] = {false, {task="PROP_HUMAN_BBQ"}, false},
	["MEDO"] = {true,{{"amb@code_human_cower_stand@male@react_cowering","base_right",1}},true},
	["AlongaLUTA"] = {false,{{"anim@deathmatch_intros@unarmed","intro_male_unarmed_e",1}},true},
	["MEDO 2"] = {true,{{"amb@code_human_cower_stand@male@react_cowering","base_right",1}},false},
	["Me da isso"] = {true,{{"anim@am_hold_up@male","shoplift_high",2}},false},
	["Qual e sua"] = {true,{{"gestures@m@standing@casual","gesture_bring_it_on",2}},false},
	["Vamos la"] = {true,{{"gestures@m@standing@casual","gesture_come_here_soft",2}},false},
	["BLZ"] = {true,{{"mp_action","thanks_male_06",1}},false},
	["Vomito Carro"] = {false,{{"oddjobs@taxi@tie","vomit_outside",1}},true},
	["DJ"] = {false,{{"anim@mp_player_intcelebrationmale@dj","dj",1}},true},
	["Eu quero ROCK"] = {false,{{"anim@mp_player_intcelebrationmale@air_guitar","air_guitar",1}},true},
	["Creu"] = {false,{{"anim@mp_player_intcelebrationfemale@air_shagging","air_shagging",1}},true},
	["Rock'n'roll"] = {false,{{"mp_player_int_upperrock","mp_player_int_rock",1}},true},
	
	
	["Sentar 2"] = {false, {task="WORLD_HUMAN_STUPOR"}, false},
	["Medico"] = {false, {task="CODE_HUMAN_MEDIC_TEND_TO_DEAD"}, false},
	["Caderno"] = {false, {task="WORLD_HUMAN_CLIPBOARD"}, false},
	["Festa"] = {false, {task="WORLD_HUMAN_PARTYING"}, false},
	["Caderno 2"] = {false, {task="CODE_HUMAN_MEDIC_TIME_OF_DEATH"}, false},
	["Fumar 2"] = {false, {task="WORLD_HUMAN_SMOKING_POT"}, false},
	["Malhar"] = {false, {task="WORLD_HUMAN_MUSCLE_FREE_WEIGHTS"}, false},
	
	["Tomar café"] = {false, {task="WORLD_HUMAN_AA_COFFEE"}, false},
	["Mendigo"] = {false, {task="WORLD_HUMAN_BUM_FREEWAY"}, false},
	["Mendigo 2"] = {false, {task="WORLD_HUMAN_BUM_SLUMPED"}, false},
	["Sinalizar"] = {false, {task="WORLD_HUMAN_CAR_PARK_ATTENDANT"}, false},
	["Apoiar-se"] = {false, {task="PROP_HUMAN_BUM_SHOPPING_CART"}, false},
	["Britadeira"] = {false, {task="WORLD_HUMAN_CONST_DRILL"}, false},
	["Festa 2"] = {false, {task="WORLD_HUMAN_DRINKING"}, false},
	["Jardineiro"] = {false, {task="WORLD_HUMAN_GARDENER_LEAF_BLOWER"}, false},
	["Jardineiro 2"] = {false, {task="WORLD_HUMAN_GARDENER_PLANT"}, false},
	["Malhar 2"] = {false, {task="WORLD_HUMAN_LEANING"}, false},
	["Violão"] = {false, {task="WORLD_HUMAN_MUSICIAN"}, false},
	["Festa 3"] = {false, {task="WORLD_HUMAN_STRIP_WATCH_STAND"}, false},
	
	["Lavar Rosto na Praia"] = {false, {task="WORLD_HUMAN_BUM_WASH"}, false},
	["Varrer Chao"] = {false, {task="WORLD_HUMAN_JANITOR"}, false},
	["Passar um Pano"] = {false, {task="WORLD_HUMAN_MAID_CLEAN"}, false},
	["Puxar Lanterna"] = {false, {task="WORLD_HUMAN_SECURITY_SHINE_TORCH"}, false},
	["Raquete de Tenis"] = {false, {task="WORLD_HUMAN_TENNIS_PLAYER"}, false},
	["Pegar Mapa"] = {false, {task="WORLD_HUMAN_TOURIST_MAP"}, false},
	["Olhar pelo Celular"] = {false, {task="WORLD_HUMAN_TOURIST_MOBILE"}, false},
	["Consertando Veiculo"] = {false, {task="WORLD_HUMAN_VEHICLE_MECHANIC"}, false},
	["Satanas"] = {false, {task="WORLD_DOG_BARKING_ROTTWEILER"}, false},
	["Puxar Barra"] = {false, {task="PROP_HUMAN_MUSCLE_CHIN_UPS"}, false},
	["Encostar e usar Celular"] = {false, {task="EAR_TO_TEXT"}, false},
	
	
	["Dança 1"] = {false,{{"anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", "mi-hi_amb_club_10_v1_male^6",1}},true},
	["Dança 2"] = {false,{{"amb@code_human_in_car_mp_actions@dance@bodhi@ds@base", "idle_a_fp",1}},true},
	["Dança 3"] = {false,{{"amb@code_human_in_car_mp_actions@dance@bodhi@rds@base", "idle_b",1}},true},
	["Dança 4"] = {false,{{"amb@code_human_in_car_mp_actions@dance@std@ds@base", "idle_a",1}},true},
	["Dança 5"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_male^6",1}},true},
	["Dança 6"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj@low_intesnsity", "li_dance_facedj_09_v1_male^6",1}},true},
	["Dança 7"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", "trans_dance_facedj_hi_to_li_09_v1_male^6",1}},true},
	["Dança 8"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_low_intensity", "trans_dance_facedj_li_to_hi_07_v1_male^6",1}},true},
	["Dança 9"] = {false,{{"anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_13_v2_male^6",1}},true},
	["Dança 10"] = {false,{{"anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", "trans_dance_crowd_hi_to_li__07_v1_male^6",1}},true},
	["Dança 11"] = {false,{{"anim@amb@nightclub@dancers@crowddance_single_props@hi_intensity", "hi_dance_prop_13_v1_male^6",1}},true},
	["Dança 12"] = {false,{{"anim@amb@nightclub@dancers@crowddance_single_props_transitions@from_med_intensity", "trans_crowd_prop_mi_to_li_11_v1_male^6",1}},true},
	["Dança 13"] = {false,{{"anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "med_center_up",1}},true},
	["Dança 14"] = {false,{{"anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", "med_right_up",1}},true},
	["Dança 15"] = {false,{{"anim@amb@nightclub@dancers@crowddance_groups@low_intensity", "li_dance_crowd_17_v1_male^6",1}},true},
	["Dança 16"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_med_intensity", "trans_dance_facedj_mi_to_li_09_v1_male^6",1}},true},
	["Dança Rak xD"] = {false,{{"special_ped@zombie@monologue_4@monologue_4l", "iamtheundead_11",1}},true},
	["Dança 17"] = {false,{{"timetable@tracy@ig_5@idle_b", "idle_e",1}},true},
	["Dança 18"] = {false,{{"mini@strip_club@idles@dj@idle_04", "idle_04",1}},true},
	["Dança 19"] = {false,{{"special_ped@mountain_dancer@monologue_1@monologue_1a", "mtn_dnc_if_you_want_to_get_to_heaven",1}},true},
	["Dança 20"] = {false,{{"special_ped@mountain_dancer@monologue_4@monologue_4a", "mnt_dnc_verse",1}},true},
	["Dança 21"] = {false,{{"special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag",1}},true},
	["Dança 22"] = {false,{{"anim@amb@nightclub@dancers@black_madonna_entourage@", "hi_dance_facedj_09_v2_male^5",1}},true},
	["Dança 23"] = {false,{{"anim@amb@nightclub@dancers@crowddance_single_props@", "hi_dance_prop_09_v1_male^6",1}},true},
	["Dança 24"] = {false,{{"anim@amb@nightclub@dancers@dixon_entourage@", "mi_dance_facedj_15_v1_male^4",1}},true},
	["Dança 25"] = {false,{{"anim@amb@nightclub@dancers@podium_dancers@", "hi_dance_facedj_17_v2_male^5",1}},true},
	["Dança 26"] = {false,{{"anim@amb@nightclub@dancers@tale_of_us_entourage@", "mi_dance_prop_13_v2_male^4",1}},true},
	["Dança 27"] = {false,{{"misschinese2_crystalmazemcs1_cs", "dance_loop_tao",1}},true},
	["Dança 28"] = {false,{{"misschinese2_crystalmazemcs1_ig", "dance_loop_tao",1}},true},
	["Dança 29"] = {false,{{"anim@mp_player_intcelebrationfemale@uncle_disco", "uncle_disco",1}},true},
	["Dança 30"] = {false,{{"anim@mp_player_intcelebrationfemale@raise_the_roof", "raise_the_roof",1}},true},
	["Dança 31"] = {false,{{"anim@mp_player_intcelebrationmale@cats_cradle", "cats_cradle",1}},true},
	["Dança 32"] = {false,{{"anim@mp_player_intupperbanging_tunes", "idle_a",1}},true},
	["Dança 33"] = {false,{{"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center",1}},true},
	["Dança 34"] = {false,{{"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center",1}},true},
	["Dança 35"] = {false,{{"anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", "high_center",1}},true},
	["Dança 36"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj_transitions@", "trans_dance_facedj_hi_to_mi_11_v1_female^6",1}},true},
	["Dança 37"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", "trans_dance_facedj_hi_to_li_07_v1_female^6",1}},true},
	["Dança 38"] = {false,{{"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_female^6",1}},true},
	["Dança 39"] = {false,{{"anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", "hi_dance_crowd_09_v1_female^6",1}},true},
	["Dança 40"] = {false,{{"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_06_base_laz",1}},true},
	
}

return cfg
